### PR TITLE
Fix unread feed selection in FoldersAndFeedsQueryBuilder

### LINKED ISSUE #255: [Bug] The feed list displayed in the drawer is confusing
**Describe the bug**
I don't really understand how the feed list displayed in the drawer in populated. It doesn't feature all the feed I subscribed to, but it also not seem to be related to the read/unread filter. It just seems to add feeds as they display new unread articles. I'm not really sure if it's a bug or a feature that confuses me. To me, it should display either all the feeds or only those that have unread items.

 

**To Reproduce**
1. Login to an account (tested on FreshRSS) 
2. Only feeds with unread item will display, 
3. As refresh goes, new feeds with unread item will display but the previous feeds, event those without unread items are still there. 

**Expected behavior**
Feeds displayed in the drawer should be updated with the read/unread filter. 

**Environment information (please complete the following information):**
 - Account type: FreshRSS
 - App version: 2.0.3
 - Android version: Android 16
 - Device type: OnePlus 5t
 - Store: F-Droid
 
**Additional context**
Maybe this deserve another issue but the feeds displayed in the drawer seem kind of duplicate with the feed tab.

### PR DESCRIPTION
**Pull request by christophehenry**
Fixes #255.

### CODE REVIEW

File: db/src/main/java/com/readrops/db/queries/FoldersAndFeedsQueryBuilder.kt [hunk 1]
```diff
@@ -51,11 +52,24 @@ object FoldersAndFeedsQueryBuilder {
...
+            append(FEED_JOIN)
+            if (hideReadFeeds) {
+                append(ITEM_JOIN)
+                if(useSeparateState) append(SEPARATE_STATE)
+            }
+        }
+        val selection = buildString {
+            append(FEED_SELECTION)
+            if (hideReadFeeds) {
+                if(useSeparateState) append("AND (ItemState.read = 0 OR ItemState.read IS NULL)")
```
Comment (Shinokuni) [inline db/src/main/java/com/readrops/db/queries/FoldersAndFeedsQueryBuilder.kt:69]: So I tested your solution and it didn't work for me, I still had some feeds and folders with 0 unread items displayed in the drawer.

And the catch is here. `ItemState` table isn't a perfect representation of the remote database. During synchronization only a limited read/unread ids are fetched. That's why when no state for an item is available in `ItemState`, we consider this item read. So in `AND (ItemState.read = 0 OR ItemState.read IS NULL)`, `ItemState.read IS NULL` shouldn't be here to get only feeds with unread items whose read state is available in `ItemState`.

**Comment by Shinokuni** [comment]
I'm adding this in addition to the comment just above. I had written a test in `GetFoldersWithFeedsTest`, could you add some to cover `hideReadFeeds` and `useSeparateState` cases? Currently there is only one test which covers `useSeparateState=false` and `hideReadFeeds=false`.

Lastly, I haven't forgotten about #263. To answer to your [last comment](https://github.com/readrops/Readrops/pull/263#issuecomment-2663177284), please know I'm open to optimization and simplification. It's just that when you opened the PR, as stated in [here](https://github.com/readrops/Readrops/pull/263#issuecomment-2660979573), your solution wasn't satisfying enough. But now you tell me that you have iterated on it and consider meeting my requirements, I will take a look at it.

Please also note that as Readrops 2.1 is around the corner, it is currently in feature freeze state. I would like for the release before merging any work of this kind.

**Comment by Shinokuni** [comment]
> I'm sorry to read that. Unfortunately, in the current state of the code, I can't progres any further. The creation of this SQL query is too complex for me.

Oh, I should have been more clearer. Your solution works if you remove `ItemState.read IS NULL` from `if(useSeparateState) append("AND (ItemState.read = 0 OR ItemState.read IS NULL)")` in `FoldersAndFeedsQueryBuilder`.  That's why I made a review on that specific line. Could you just modify this in order to merge?

Otherwise I understand if you don't want to work on this subject anymore, I will handle tests myself.

**Comment by christophehenry** [comment]
Ah right, sorry. Done. I added a test too.

**Comment by Shinokuni** [comment]
Alright, thanks for this!
